# Generated by Django 5.1.4 on 2025-02-06 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_persona_apellido1_alter_persona_apellido2_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bautizo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "nombre_nino",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Niño/Niños"
                    ),
                ),
                (
                    "nombre_padre",
                    models.CharField(max_length=200, verbose_name="Nombre del Padre"),
                ),
                (
                    "nombre_madre",
                    models.CharField(max_length=200, verbose_name="Nombre de la Madre"),
                ),
                ("padrinos", models.CharField(max_length=200)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
