# Generated by Django 5.1.4 on 2025-02-08 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_matrimonio"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservamisa",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                ],
                default="pendiente",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reservamisa",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
