# Generated by Django 5.1.3 on 2025-02-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_matrimonio_estado_matrimonio_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservamisa',
            name='hora',
        ),
    ]
