# Generated by Django 5.1.3 on 2025-02-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_reservamisa_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bautizo',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='matrimonio',
            name='hora',
        ),
    ]
